Add estado de SC e info cidade Joinville
turicas/covid19-br pull request #31
Opened 2020-03-23 06:27 UTC by Mat-Bit

Como até o momento não tem uma fonte centralizada de informações para o estado de Santa Catarina, fiz o `corona_sc_spider.py` com base (tentei) no já feito do PR, tendo que por o nome e link para informações de cada cidade.

No momento possui apenas a cidade de Joinville.

2020-03-23 17:59 UTC, endersonmaia requested changes
@Mat-Bit remove o `./scripts/.spyproject/*` aí do commit

2020-03-23 18:00 UTC, endersonmaia requested changes
remove esse SC_IBGE.xls, que é binário, e não deveria estar no repositório

2020-03-23 18:01 UTC, endersonmaia requested changes
o que tiver dentro de ./data/output/*.csv também acredito que não deva estar dentro do commit

2020-03-23 18:01 UTC, endersonmaia commented
depois dos reviews, sugiro fazer um `git rebase -i master` para resolver os conflitos e normalizar as mensagens de commit

2020-03-24 00:32 UTC, Mat-Bit commented
Obrigado pelos comentários @endersonmaia 
Primeira vez que participo de um projeto do tipo e essa foi minha primeira PR, por isso peço um pouco de paciência com o iniciante aqui...

Farei as alterações sugeridas o quanto antes, e como são algumas, acha melhor excluir essa pull request e fazer outra depois das alterações?

2020-03-24 01:11 UTC, endersonmaia commented
@Mat-Bit sem problemas

não vejo pq criar outra PR, faz as alterações, mesmo que vc modifique os commits e/ou o histórico, podes sobrepor a branch com `push --force`, o importante é que não haja conflitos com a `master`

eu criaria uma branch a parte, fica mais fácil de manter-se atualizado

se ficar com alguma dúvida, pode comentar aqui

2020-03-25 04:31 UTC, Mat-Bit commented
Atualizei o repositório e creio que realizei as modificações necessárias...

2020-03-25 12:36 UTC, endersonmaia approved these changes

2020-03-25 12:42 UTC, endersonmaia commented
@turicas fiz um review aí do commit, tá bem resumido agora

não atentei pra implementação python, depois dá uma olhada aí

2020-03-25 19:23 UTC, turicas requested changes
Revisado, mas lembrando: ainda usamos como fonte oficial os dados das secretarias estaduais (porém esse script pode ser útil pra outras pessoas e talvez no futuro possamos usar também).

2020-03-25 19:23 UTC, turicas commented on corona_sc_spider.py
> +	data_cities = {
Esse dict poderia ser uma lista criada no __init__ e então o método que salva os dados poderia só adicionar um dicionário a essa lista.

2020-03-25 19:23 UTC, turicas commented on corona_sc_spider.py
> +		df_city_sc = pd.read_csv(DATA_PATH / Path("populacao-estimada-2019.csv"))
Aqui não precisamos da dependência do pandas (qualquer dependencia extra adiciona tempo de build da imagem). Poderia usar o csv.DictReader  ou rows.import_from_csv.

2020-03-25 19:23 UTC, turicas commented on corona_sc_spider.py
> +		cities_sc = df_city_sc.iloc[4418:4711,3].values
Acho bem arriscado pegar pelo número assim. Poderia ser:
```python
cities = rows.import_from_csv(...)  # essa linha poderia estar no __init__
joinville = [row for row in cities if row.uf == "SC" and row.municipio == "Joinville"][0]
```

2020-03-25 19:23 UTC, turicas commented on corona_sc_spider.py
> +		df_out = pd.DataFrame.from_dict(CoronaScSpider.data_cities)
Novamente aqui: não precisa do Pandas. Dá pra usar table = rows.import_from_dicts e table.order_by("city")

2020-03-25 19:23 UTC, turicas commented on corona_sc_spider.py
> +		df_out.to_csv(filename, index=False)
Se tiver mais de uma cidade essa linha vai sobrescrever o arquivo.
Sugiro uma outra abordagem: usar o output do proprio scrapy  ou mesmo ter um csv DictWriter (que pode ser um rows.utils.CsvLazyDictWriter) iniciado no __init__ e só chamar o self.writer.writerow aqui.

2020-03-28 21:01 UTC, Mat-Bit commented on corona_sc_spider.py
> +		df_city_sc = pd.read_csv(DATA_PATH / Path("populacao-estimada-2019.csv"))
Realmente, não conhecia direito essa biblioteca, mas dei uma lida e achei melhor do que o próprio pandas para essa aplicação! muito bom!

2020-03-28 21:01 UTC, Mat-Bit commented on corona_sc_spider.py
> +		cities_sc = df_city_sc.iloc[4418:4711,3].values
Realmente.. fiz essa alteração que sugeriu também.

2020-03-28 21:02 UTC, Mat-Bit commented on corona_sc_spider.py
> +		df_out = pd.DataFrame.from_dict(CoronaScSpider.data_cities)
usei o `rows.import_from_dicts`

2020-03-28 21:03 UTC, Mat-Bit commented on corona_sc_spider.py
> +		df_out.to_csv(filename, index=False)
Realmente, ainda tenho que pesquisar melhor como usar o output do scrapy, essa pendência não consegui resolver ainda..

2020-03-28 21:04 UTC, turicas commented on corona_sc_spider.py
> +		df_out.to_csv(filename, index=False)
Veja no `collect.sh`, lá rodamos o `scrapy runspider` com a opção `-o arquivo.csv`.

2020-03-28 21:08 UTC, Mat-Bit commented
Obrigado pela revisão e sugestões @turicas !

Sei que idealmente o certo seria pegar um só link da Secretaria Estadual de Saúde com as informações dos municípios, porém ainda não encontrei um portal que reunisse toda a informação em um só lugar.

Paliativamente pensei em contribuir fazendo por cidades em que há notificações sobre a doença..

Acredito que consegui fazer as alterações requisitadas, com exceção de sobrescrever o documentos toda vez que executa o método `parse()`.

Assim que possível farei o restante das alterações.

2020-04-02 14:29 UTC, turicas commented
Pessoal, atualização sobre os crawlers e a forma como estamos preenchendo os dados: vamos mudar a forma de subida dos dados pra facilitar o trabalho dos voluntários e deixar o processo mais robusto e confiável e, com isso, será mais fácil que robôs possam subir também os dados; dessa forma, os scrapers ajudarão *bastante* no processo. Com isso, criei algumas regras gerais e em breve farei algumas atualizações sobre:

- **Necessário** fazer o scraper usando o `scrapy`;
- **Não usar** `pandas`, `BeautifulSoap`, `requests` ou outras bibliotecas desnecessárias (a std lib do Python já tem muita biblioteca útil, o `scrapy` com XPath já dá conta de boa parte das raspagens e `rows` já é uma dependênciad esse repositório);
- Deve existir alguma maneira fácil de fazer o scraper coletar os boletins e casos para uma data específica;
- O método de parsing deve devolver (com `yield`) um dicionário com as seguintes chaves:
  - `date`: data no formato `"YYYY-MM-DD"`
  - `state`: sigla do estado, com 2 caracteres maiúsculos (deve ser um atributo da classe do spider e usar `self.state`)
  - `city` (nome do município ou em branco, caso seja o valor do estado, deve ser `None`)
  - `place_type`: `"city"` para município e `"state"` para estado
  - `confirmed`: inteiro, número de casos confirmados (ou `None`)
  - `deaths`: inteiro, número de mortes naquele dia (ou `None`)
  - **ATENÇÃO**: o scraper deve devolver sempre um registro para o estado que *não seja* a soma dos valores por município (esse dado deve ser extraído da linha "total no estado" no boletim) - essa linha virá com a coluna `city` com o valor `None` e `place_type` com `"state"`;
- Quando possível, use testes automatizados.

Nesse momento não temos muito tempo disponível para revisão, então *por favor*, só crie um pull request sugerindo com código de um novo scraper caso você possa cumprir os requisitos acima.

2024-05-15 19:45 UTC, closed without merging